#!/bin/bash
set -e

USER_HOME="/home/droidian"
GTK_CONFIG_DIR="$USER_HOME/.config/gtk-3.0"
GTK_SOURCE="/usr/share/dlsos/config/gtk.css"
WALLPAPER_PATH="/usr/share/backgrounds/wallpaper_dlsos.png"

# Créer le dossier de config s'il n'existe pas
if [ ! -d "$GTK_CONFIG_DIR" ]; then
  mkdir -p "$GTK_CONFIG_DIR"
  chown droidian:droidian "$GTK_CONFIG_DIR"
fi

# Copier gtk.css depuis le paquet vers le home de l'utilisateur
if [ -f "$GTK_SOURCE" ]; then
  cp -f "$GTK_SOURCE" "$GTK_CONFIG_DIR/"
  chown droidian:droidian "$GTK_CONFIG_DIR/gtk.css"
else
  echo "[!] Fichier $GTK_SOURCE introuvable, impossible de copier gtk.css"
fi

# Configuration du thème Plymouth
PLYMOUTH_THEME_NAME="dlsos"
PLYMOUTH_THEME_PATH="/usr/share/plymouth/themes/$PLYMOUTH_THEME_NAME/$PLYMOUTH_THEME_NAME.plymouth"

if [ -f "$PLYMOUTH_THEME_PATH" ]; then
    update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth "$PLYMOUTH_THEME_PATH" 100
    update-alternatives --set default.plymouth "$PLYMOUTH_THEME_PATH"
    update-initramfs -u
    echo "[+] Plymouth mis à jour avec succès."
else
    echo "[!] Fichier $PLYMOUTH_THEME_PATH introuvable."
fi

exit 0

